image: maven:3.8.1-jdk-11

stages:
  - build
  - test

services:
  - selenium/standalone-chrome:latest

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository

before_script:
  - export DISPLAY=:99.0
  - mvn --version
  - google-chrome --version

build:
  stage: build
  script:
    - mvn $MAVEN_OPTS clean install
  artifacts:
    paths:
      - target/*.jar

test:
  stage: test
  script:
    - mvn $MAVEN_OPTS test
  artifacts:
    when: always
    paths:
      - target/surefire-reports
      - target/failsafe-reports
  only:
    - master
    - merge_requests
