image: maven:3.8.1-jdk-11

stages:
  - build
  - test

cache:
  paths:
    - .m2/repository

variables:
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"

before_script:
  - echo "Maven project is building..."

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean install
  artifacts:
    paths:
      - target/*.jar

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test
  artifacts:
    paths:
      - target/surefire-reports
      - target/failsafe-reports
  only:
    - master
    - merge_requests
