name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 20 on Windows
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'temurin'
          cache: maven

      - name: Set up ChromeDriver on Windows
        uses: browser-actions/setup-chrome@v1

      - name: Set up GeckoDriver (Firefox) on Windows
        run: |
          choco install firefox
          choco install geckodriver

      - name: Set up EdgeDriver on Windows
        run: |
          choco install microsoft-edge
          choco install msedgedriver

      - name: Build and Test on Windows (Chrome)
        run: mvn compile test -Dbrowser=chrome -Dsurefire.suiteXmlFiles=src/main/resources/testsuites/SmokeTest.xml

      - name: Build and Test on Windows (Firefox)
        run: mvn compile test -Dbrowser=firefox -Dsurefire.suiteXmlFiles=src/main/resources/testsuites/SmokeTest.xml

      - name: Build and Test on Windows (Edge)
        run: mvn compile test -Dbrowser=edge -Dsurefire.suiteXmlFiles=src/main/resources/testsuites/SmokeTest.xml

  test_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 20 on macOS
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'temurin'
          cache: maven

      - name: Set up ChromeDriver on macOS
        uses: browser-actions/setup-chrome@v1

      - name: Set up GeckoDriver (Firefox) on macOS
        run: brew install geckodriver

      - name: Set up EdgeDriver on macOS
        run: brew install --cask microsoft-edge

      - name: Build and Test on macOS (Chrome)
        run: mvn compile test -Dbrowser=chrome -Dsurefire.suiteXmlFiles=src/main/resources/testsuites/SmokeTest.xml

      - name: Build and Test on macOS (Firefox)
        run: mvn compile test -Dbrowser=firefox -Dsurefire.suiteXmlFiles=src/main/resources/testsuites/SmokeTest.xml

      - name: Build and Test on macOS (Edge)
        run: mvn compile test -Dbrowser=edge -Dsurefire.suiteXmlFiles=src/main/resources/testsuites/SmokeTest.xml

  test_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 20 on Ubuntu
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'temurin'
          cache: maven

      - name: Set up ChromeDriver on Ubuntu
        uses: browser-actions/setup-chrome@v1

      - name: Set up GeckoDriver (Firefox) on Ubuntu
        run: |
          sudo apt-get update
          sudo apt-get install -y firefox
          wget https://github.com/mozilla/geckodriver/releases/download/v0.30.0/geckodriver-v0.30.0-linux64.tar.gz
          tar -xzf geckodriver-v0.30.0-linux64.tar.gz
          sudo mv geckodriver /usr/local/bin/
          rm geckodriver-v0.30.0-linux64.tar.gz

      - name: Set up EdgeDriver on Ubuntu
        run: |
          wget https://msedge.sf.dl.delivery.mp.microsoft.com/filestreamingservice/files/44fbd734-8020-4ed8-bbda-9b1cf8e139e2/MicrosoftEdge-Dev_91.0.864.15-1_amd64.deb
          sudo dpkg -i MicrosoftEdge-Dev_91.0.864.15-1_amd64.deb
          sudo apt-get install -f
          sudo apt-get install msedge

      - name: Build and Test on Ubuntu (Chrome)
        run: mvn compile test -Dbrowser=chrome -Dsurefire.suiteXmlFiles=src/main/resources/testsuites/SmokeTest.xml

      - name: Build and Test on Ubuntu (Firefox)
        run: mvn compile test -Dbrowser=firefox -Dsurefire.suiteXmlFiles=src/main/resources/testsuites/SmokeTest.xml

      - name: Build and Test on Ubuntu (Edge)
        run: mvn compile test -Dbrowser=edge -Dsurefire.suiteXmlFiles=src/main/resources/testsuites/SmokeTest.xml
